name: Autograding Tests
'on':
    schedule:
      - cron: '20 6 10 4 *'
permissions:
  checks: write
  actions: read
  contents: write
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    if: 'github.actor != ''github-classroom[bot]'''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update repo to the newest version
        run: |
          curl -O https://raw.githubusercontent.com/Shiritai/xv6-ntu-mp2/refs/heads/ntuos/mp2-submit/mp2.sh
          chmod +x mp2.sh
          ./mp2.sh update

      - name: Decrypt Private Tests
        run: >
          openssl enc -aes-256-cbc -d -in test/private_tests.zip.enc -out
          test/private.zip -k ${{ secrets.DECRYPT_PASSWORD }} -pbkdf2

      - name: Unzip Private Tests
        run: cd test && unzip private.zip

      - name: Pull Image
        run: ./mp2.sh pull

      - name: Run all the tests
        id: test-all
        run: |
          scripts/action_grader.sh
        shell: bash

      - name: Submit mp2 grade
        id: submit-grade
        run: |
          STUDENT_ID=$(cat ./student_id.txt)
          git config --global user.name "Student Bot $STUDENT_ID"
          git config --global user.email "student$STUDENT_ID@github.com"

          REPORT=${STUDENT_ID}-report.txt
          git add $REPORT
          git commit -m "[TA] Submit MP2 grade for $STUDENT_ID"
          git push
        shell: bash
